# Este es un archivo de configuración para Nginx.
# Le dice al servidor que escuche en el puerto especificado por la variable de entorno $PORT.
# Cloud Run establecerá esta variable en 8080.
server {
    listen       ${PORT};
    server_name  localhost;

    # Sirve la aplicación de React desde la raíz.
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Esta línea es importante para que el enrutamiento del lado del cliente (React Router) funcione.
        # Si no se encuentra un archivo, se sirve el index.html.
        try_files $uri $uri/ /index.html;
    }

    # Redirige los logs de errores y de acceso a la salida estándar para que
    # Cloud Run pueda capturarlos y mostrarlos.
    error_log  /dev/stderr;
    access_log /dev/stdout;
}
